### ISSUE TITLE
Investigate what dependancies are required for our project 

### ISSUE THREAD

**Issue by Sampsonyu** [UBC-MDS/What-Effects-One-Chance-of-Survival-on-the-Titanic-A-Logistic-Regression-Analysis#21] opened 2023-11-22 00:58 UTC

**Comment by fohy24** [comment] 2023-11-22 00:59
Hey guys I have the version list:
dependencies:
    - python=3.11.*
    - pip=23.3
    - ipykernel=6.25.0
    - nb_conda_kernels=2.3.1
    - panel=1.3.1
    - r-base>=4.1
    - r-essentials=1.7.0
    - r-devtools=2.4.5
    - r-gert=2.0.0
    - r-usethis=2.2.0
    - r-testthat=3.2.0
    - r-startup=0.20.0
    - r-rmarkdown=2.22
    - r-stringi=1.8.1
    - r-tidyverse=2.0.0
    - r-hmisc=5.1_1
    - r-rjson=0.2.21
    - r-ggally=2.1.2
    - r-ggthemes=4.2.4
    - r-cowplot=1.1.1
    - r-irkernel=1.3.2
    - r-titanic=0.1.0 #Titanic Data
    - r-knitr=1.43
    - r-gridExtra=2.3
    - r-dplyr=1.1.4
    - pip:
        titanic

**Comment by fohy24** [comment] 2023-11-22 17:45
Hi everyone the following code (already in the Dockerfile) can install the R packages we need (I suppose they are from the base image). I checked in the container that the libraries installed this way can be called successfully. 

RUN mamba install --yes \
    'r-base' \
    'r-caret' \
    'r-crayon' \
    'r-devtools' \

Any concern if we append to the list instead of running `RUN R -e "install.packages('testthat', version='3.2.0', repos='http://cran.rstudio.com/')"` for all packages?

**Comment by Sampsonyu** [comment] 2023-11-22 17:58
This looks clear and well-organized. I think it is a better solution. Just one concern, how do we specify the version in this way?

**Comment by alanpow** [comment] 2023-11-22 20:20
Looks like what I read online I think this is good. Also the versions are specified?

**Comment by fohy24** [comment] 2023-11-22 22:01
The template code from the base image doesn't specify versions, but still does its job.

**Comment by karan-khubdikar** [comment] 2023-11-23 03:40
I guess we should all download the docker container on our respective laptops and try running the notebook after building the docker image. That would be a good check to ensure that our container is working fine.

**Comment by fohy24** [comment] 2023-11-23 05:32
I tried the RUN mumba install command for all our dependencies and everything seems to be installed properly. I didnt specify version number though. Maybe we can all try to run this Dockerfile? 
[Dockerfile.zip](https://github.com/UBC-MDS/What-Effects-One-Chance-of-Survival-on-the-Titanic-A-Logistic-Regression-Analysis/files/13446331/Dockerfile.zip)

**Comment by karan-khubdikar** [comment] 2023-11-25 00:41
I am able to build the docker file and run the Jupyter notebook as well. I guess we now need to do the docker compose to have our files and folder accessible in container.

**Comment by alanpow** [comment] 2023-11-25 22:23
Looks like we finished this one up a while ago I will close it for now, good stuff guys!

**Closed by alanpow** 2023-11-25 22:23 UTC
